version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: aegis
      POSTGRES_PASSWORD: aegis
      POSTGRES_DB: aegis
    ports:
      - "5432:5432"
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
  auth-service:
    build: ./services/auth-service
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgres://aegis:aegis@postgres:5432/aegis?sslmode=disable
    ports:
      - "8000:8000"
  integrations-service:
    build: ./services/integrations-service
    depends_on:
      - postgres
      - rabbitmq
    environment:
      - DATABASE_URL=postgres://aegis:aegis@postgres:5432/aegis?sslmode=disable
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
    ports:
      - "8001:8001"
  scanner-service:
    build: ./services/scanner-service
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
  results-service:
    build: ./services/results-service
    depends_on:
      - postgres
      - rabbitmq
    environment:
      - DATABASE_URL=postgres://aegis:aegis@postgres:5432/aegis?sslmode=disable
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
    ports:
      - "8002:8002"
  remediation-service:
    build: ./services/remediation-service
    ports:
      - "8003:8003"
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - auth-service
      - integrations-service
      - results-service
